version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: bankpass
      POSTGRES_DB: bankdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./backend
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000
             --ssl-keyfile /certs/localhost-key.pem
             --ssl-certfile /certs/localhost.pem"
    volumes:
      - ./backend:/code
      - ./certs:/certs          # certificados mkcert
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  db_data:
